### ISSUE TITLE
How to get charachter level bounding boxes instead of word level boxes ? 

### ISSUE THREAD

**Issue by raghavgurbaxani** [mingliangzhang2018/EAST-Pytorch#4]
Is there some way I can get character-level annotation boxes as output instead of the word-level annotation ones?

Thanks ,

**Comment by ZhangMingliangAI** [comment]
> Is there some way I can get character-level annotation boxes as output instead of the word-level annotation ones?
> 
> Thanks ,

Character-level detection is feasible but you do need manual labeling. Some annotation tools are worth using such as jinglingbiaozhu software.
